vcptUnit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vcptUnit_home.urls', namespace='vcptUnit_home')),
    path('vcptu-contact', include('vcptUnit_contact.urls', namespace='vcptUnit_contact')),
    path('about-vcptu', include('vcptUnit_aboutUs.urls', namespace='vcptUnit_aboutus')),
    path('vcptu-services', include('vcptUnit_service.urls', namespace='vcptUnit_service')),
    path('vcptu-facility', include('vcptUnit_facility.urls', namespace='vcptUnit_facility')),
    path('vcptu-publication', include('vcptUnit_publication.urls', namespace='vcptUnit_publication')),
    path('vcptu-projects', include('vcptUnit_projects.urls', namespace='vcptUnit_projects')),
    path('vcptu-accreditation', include('vcptUnit_accreditations.urls', namespace='vcptUnit_accreditations')),
    path('vcptu-news', include('vcptUnit_news.urls', namespace='vcptUnit_news')),
    # path('vcptu-reports', include('vcptUnit_reports.urls', namespace='vcptUnit_reports')),
    path('vcptu-team', include('vcptUnit_team.urls', namespace='vcptUnit_team')),
    path('vcptu-gallery', include('vcptUnit_gallery.urls', namespace='vcptUnit_gallery')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

vcptUnit_team/urls.py
from django.urls import path
from . import views

# urlsPatterns

app_name = 'vcptUnit_team'

urlpatterns = [
   path('', views.teamPage, name='teamPage'),
   path('staff-detail', views.detailView, name='detailView'),
   path('staff-detail-dr-saraah-Moore', views.SaraahMooredetailView, name='SaraahMooredetailView'),
   path('staff-detail-jason-Moore', views.JasonMooredetailView, name='JasonMooredetailView'),
   path('staff-detail-kyeba-swai', views.swaiDetailView, name='swaiDetailView'),
   path('staff-detail-Emmanuel-Mbuba', views.EmmanuelMbubaDetailView, name='EmmanuelMbubaDetailView'),
   path('staff-detail-Rose-Philipo', views.RosePhilipoDetailView, name='RosePhilipoDetailView'),
   
]

vcptUnit_team/models.py
from django.db import models
import uuid
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.
class VcptuTeamModal(models.Model):
    UNIT_CATEGORY = (
        ('', 'Select Staff Tilte'),
        ('Core Management Team', 'Core Management Team'),
        ('Technicians', 'Technicians'),
        ('Data managers', 'Data managers'),
        ('Administrative officers', 'Administrative officers')
    )
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    staff_image = models.ImageField(upload_to='media/')
    staff_name = models.CharField(max_length= 100, null=True, blank=True)
    professional_or_title = models.CharField(max_length=100,null=True, blank=True)
    unity_category = models.CharField(max_length=100, null=True, blank=True, choices=UNIT_CATEGORY)
    profile_descriptions = RichTextField()
    posted_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='staff_profile_content_posted_by')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name_plural = 'VCPTU-Team'

    def __str__(self):
        return f'{str(self.staff_name)}'

vcptUnit_team/views.py
from django.shortcuts import render

# Create your views here.
def teamPage(request):
    template_name = 'vcptUnit_team/teamPage.html'
    context = {

    }
    return render(request, template_name, context)


def detailView(request):
    template_name = 'vcptUnit_team/detailView.html'
    context = {

    }
    return render(request, template_name, context)


def SaraahMooredetailView(request):
    template_name = 'vcptUnit_team/SaraahMooredetailView.html'
    context = {

    }
    return render(request, template_name, context)

def JasonMooredetailView(request):
    template_name = 'vcptUnit_team/JasonMooredetailView.html'
    context = {

    }
    return render(request, template_name, context)

def swaiDetailView(request):
    template_name = 'vcptUnit_team/swaiDetailView.html'
    context = {

    }
    return render(request, template_name, context)

def EmmanuelMbubaDetailView(request):
    template_name = 'vcptUnit_team/EmmanuelMbubaDetailView.html'
    context = {

    }
    return render(request, template_name, context)

def RosePhilipoDetailView(request):
    template_name = 'vcptUnit_team/RosePhilipoDetailView.html'
    context = {

    }
    return render(request, template_name, context)

templates/vcptUnit_team/EmmanuelMbubaDetailView.html
{% extends '../baseTemplates/websiteBase.html' %}
{% load static %}
{% block title %} Team {% endblock %}
{% block content %}
<div class="connt">
    <div class="detail_view_section" style="height:100vh;position:sticky;top:120px;bottom:0px;margin:-50px 0px;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="inner_section">
                        <div class="image_section" style="background-color:white;">
                            <h1 style="background-color: white;padding-bottom: 20px;color:green;">Emmanuel Mbuba</h1>
                            <img src="{% static './images/staff/EmmanuelMbuba_original web.png' %}" alt="" class="img-fluid" style="width:100%;">
                        </div>
                        <div class="description">
                            <h2>Study Director</h2>
                            <p style="padding: 10px 0px;line-height: 30px;">Kyeba Swai is a result-driven medical entomologist with ten years of accumulated experience in
								conducting and supervising semi-field and field studies collecting entomological data and its
								analysis. He is currently registered for a PhD and works at the Vector Control Product Testing Unit
								(VCPTU) primarily leading the evaluations on spatial repellents but also supports phase II
								(experimental hut) evaluations of long-lasting insecticidal nets. </p>
                                <p>
                                    Before joining VCPTU, he led
								several research projects in south eastern Tanzania including, a malaria prevalence survey across
								several villages of Ulanga district and on a project that aimed to develop low-cost and portable
								mosquito-proof houses to protect migratory rice farmers from mosquito-borne illnesses. 
                                </p>
                                <p>

                                    He is
								interested in the control of vector borne diseases, specifically in understanding the role of migratory
								livelihoods in maintaining the transmission of malaria. He is keen on developing research agendas
								that incorporate this aspect as well as the development and evaluation of novel mosquito control
								tools, particularly those that can be used by migratory communities.
                                </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="ff" style="position:static;z-index:0;display:none">
        {% include '../components/footer.html' %}
    </div>
</div>

{% endblock %}

templates/vcptUnit_team/JasonMooredetailView.html
{% extends '../baseTemplates/websiteBase.html' %}
{% load static %}
{% block title %} Team {% endblock %}
{% block content %}
<div class="connt">
    <div class="detail_view_section" style="height:100vh;position:sticky;top:120px;bottom:0px;margin:-50px 0px;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="inner_section">
                        <div class="image_section" style="background-color:white">
                            <h1 style="background-color: white;padding-bottom: 20px;color:green;">Jason Moore</h1>
                            <img src="{% static './images/staff/jasonMoore.jpg' %}" alt="" class="img-fluid">
                        </div>
                        <div class="description">
                            <h2>Test Facility Manager</h2>
                            <p style="padding: 10px 0px;line-height: 30px;">Jason Moore is currently the Test Facility Manager for the GLP accredited vector control
								product testing unit of Ifakara Health Institute. The units evaluates new vector control tools
								for pre-qualification by the World Health Organization and conducts Research and
								Development for industry and other consortiums. He has also been involved in large phase
								III studies assessing the functional life of Long Lasting Insecticidal Nets which have led to a
								greater understanding of future product profiles and policy review. He has as part of a team,
								.</p>
                            <p style="padding: 10px 0px;line-height: 30px;">worked on the development of new assays and facilities used in research at Ifakara Health
								Institute and several other African countries.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="ff" style="position:static;z-index:0;display:none">
        {% include '../components/footer.html' %}
    </div>
</div>

{% endblock %}

templates/vcptUnit_team/RosePhilipoDetailView.html
{% extends '../baseTemplates/websiteBase.html' %}
{% load static %}
{% block title %} Team {% endblock %}
{% block content %}
<div class="connt">
    <div class="detail_view_section" style="height:100vh;position:sticky;top:120px;bottom:0px;margin:-50px 0px;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="inner_section">
                        <div class="image_section" style="background-color:white;">
                            <h1 style="background-color: white;padding-bottom: 20px;color:green;">Rose Philipo</h1>
                            <img src="{% static './images/staff/rose.png' %}" alt="" class="img-fluid" style="width:100%;">
                        </div>
                        <div class="description">
                            <h2>Project Manager</h2>
                            <p style="padding: 10px 0px;line-height: 30px;">Kyeba Swai is a result-driven medical entomologist with ten years of accumulated experience in
								conducting and supervising semi-field and field studies collecting entomological data and its
								analysis. He is currently registered for a PhD and works at the Vector Control Product Testing Unit
								(VCPTU) primarily leading the evaluations on spatial repellents but also supports phase II
								(experimental hut) evaluations of long-lasting insecticidal nets. </p>
                                <p>
                                    Before joining VCPTU, he led
								several research projects in south eastern Tanzania including, a malaria prevalence survey across
								several villages of Ulanga district and on a project that aimed to develop low-cost and portable
								mosquito-proof houses to protect migratory rice farmers from mosquito-borne illnesses. 
                                </p>
                                <p>

                                    He is
								interested in the control of vector borne diseases, specifically in understanding the role of migratory
								livelihoods in maintaining the transmission of malaria. He is keen on developing research agendas
								that incorporate this aspect as well as the development and evaluation of novel mosquito control
								tools, particularly those that can be used by migratory communities.
                                </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="ff" style="position:static;z-index:0;display:none">
        {% include '../components/footer.html' %}
    </div>
</div>

{% endblock %}

templates/vcptUnit_team/SaraahMooredetailView.html
{% extends '../baseTemplates/websiteBase.html' %}
{% load static %}
{% block title %} Team {% endblock %}
{% block content %}
<div class="connt">
    <div class="detail_view_section" style="height:100vh;position:sticky;top:120px;bottom:0px;margin:-50px 0px;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="inner_section">
                        <div class="image_section" style="background-color:white;width:1900px">
                            <h1 style="background-color: white;padding-bottom: 20px;color:green;">Dr Sarah Moore</h1>
                            <img src="{% static './images/staff/Dr -saraah.png' %}" alt="" class="img-fluid">
                        </div>
                        <div class="description px-3">
                            <h2>Head of unit</h2>
                            <p style="padding: 10px 0px;line-height: 30px;">Dr. Sarah Moore is a medical entomologist specializing in the chemical ecology and control of Anopheles mosquitoes with a focus on new tools to protect individuals, households and communities. She is leading the Vector Control Product Testing Unit (VCPTU) at IHI. Dr. Moore holds a PhD in Medical Entomology.</p>
                            <p style="padding: 10px 0px;line-height: 30px;">Dr. Moore joined the Institute 14 years ago. She is also an associate professor at the Swiss Tropical and Public Health Institute (Swiss TPH) of the Basel University, Switzerland. Dr. Moore holds a PhD in Medical Entomology from the London School of Hygiene and Tropical Medicine, UK.</p>
                            <p>The VCPTU she is leading, serves the community through excellence in service delivery, research into new methods of product testing and training of MSc and PhD students</p>
                            <p>Having a diverse range of vector control tools in the malaria control toolbox has two advantages: 1) malaria control programs can select tools most suitable for their setting and 2) increasing market diversity creates competition that drives down unit costs of products.</p>

                            <p>She has Assisted World Health Organization (WHO) as a member of WHO Pesticide Evaluation Scheme (WHOPES), Technical Expert Groups (TEG) and as an ad Hoc Member of the Vector Control Advisory Group (VCAG).</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>Therefore, in order to bring new vector control products to market more rapidly and cost-efficiently there has been a global initiative to improve the quality of product evaluation.</p>
                    <p>The VCPTU team is dedicated to building capacity in entomology for the future of vector control</p>
                    <p>The team has developed several new product-testing assays including a new experimental hut and ambient chamber assays and work closely with mathematical modellers and statisticians to gather relevant data using careful experimental design and data analysis techniques.</p>


                </div>
                <div class="col-md-6 mb-5">
                    <p>Currently, Dr. Moore is supervising nine PhD candidates registered at University of Basel. These are: Lorenz Hofer, Emmanuel Mbuba, Daniel Msellemu, Isaac Namango, Mgeni Mohammed Tambwe, Elodie Vajda, Allison Tatarsky, Frank Tenywa and Kyeba Swai.</p>
                    <p>She also co-supervising Olukayode Odufuwa registered for PhD at the LSHTM.</p>
                    <p>Additionally, she is supervising three master’s students: Dismas Kamande, Stephen Mbwambo and Janeth Machange. In her teaching role of the Masters of Science in Public Health Research at IHI, Dr. is module organiser for Intervention Trials and Management as well as Scientific Reading and Writing.</p>
                    <p>Dr. Moore is experienced in product evaluation: Long Lasting Insecticidal Nets (LLINs) laboratory, semi-field and durability monitoring, Indoor Residual Spray (IRS) at laboratory, semi-field and community studies, Spatial repellents laboratory, semi-field and clinical trial, Topical repellents at laboratory, semi-field and clinical trial, Odour baited traps at semi-field, Attractive Targeted Sugar Baits at semi-field and field trials.</p>
                </div>
            </div>
        </div>
    </div>


    <div class="ff" style="position:static;z-index:0;display:none">
        {% include '../components/footer.html' %}
    </div>
</div>

{% endblock %}

templates/vcptUnit_team/detailView.html
{% extends '../baseTemplates/websiteBase.html' %}
{% load static %}
{% block title %} Team {% endblock %}
{% block content %}
<div class="connt">
    <div class="detail_view_section" style="height:100vh;position:sticky;top:120px;bottom:0px;margin:-50px 0px;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="inner_section">
                        {% if get_staff_detail %}
                       
                        <div class="col-md-4">
                            <div class="image_section"  style="width:350px;">
                            <h1 style="background-color: white;padding-bottom: 10px;color:green;">{{ get_staff_detail.staff_name }}</h1>
                            <img src="{{ get_staff_detail.staff_image.url  }}" alt="" class="img-fluid">
                        </div>
                    </div>
                        <div class="col-md-8">
                            <div class="description">
                                <h2>{{ get_staff_detail.professional_or_title }}</h2>
                                <p style="padding: 1px 0px;line-height: 30px;"> {{ get_staff_detail.profile_descriptions | safe  }}</p>
                                {% comment %} <p style="padding: 10px 0px;line-height: 30px;">Mr. Mmbaga began his data management and analysis career at IHI in 2012 as an intern and later on in 2015, after obtaining his first degree, he was employed as Data Officer. He has extensive experience in database designing and management in (MSAcess, MySQL Server, Apache). Mr. Mmbaga also has experience in software development (web and mobile applications), and data analysis using different platforms such as Stata and R.</p> {% endcomment %}
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="ff" style="position:static;z-index:0;display:none">
        {% include '../components/footer.html' %}
    </div>
</div>

{% endblock %}

templates/vcptUnit_team/swaiDetailView.html
{% extends '../baseTemplates/websiteBase.html' %}
{% load static %}
{% block title %} Team {% endblock %}
{% block content %}
<div class="connt">
    <div class="detail_view_section" style="height:100vh;position:sticky;top:120px;bottom:0px;margin:-50px 0px;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="inner_section">
                        <div class="image_section" style="background-color:white">
                            <h1 style="background-color: white;padding-bottom: 20px;color:green;">Kyeba Swai</h1>
                            <img src="{% static './images/staff/Swai-Kyeba.jpg' %}" alt="" class="img-fluid">
                        </div>
                        <div class="description">
                            <h2>Study Coordinator</h2>
                            <p style="padding: 10px 0px;line-height: 30px;">Kyeba Swai is a result-driven medical entomologist with ten years of accumulated experience in
								conducting and supervising semi-field and field studies collecting entomological data and its
								analysis. He is currently registered for a PhD and works at the Vector Control Product Testing Unit
								(VCPTU) primarily leading the evaluations on spatial repellents but also supports phase II
								(experimental hut) evaluations of long-lasting insecticidal nets. Before joining VCPTU, he led
								several research projects in south eastern Tanzania including, a malaria prevalence survey across
								several villages of Ulanga district and on a project that aimed to develop low-cost and portable
								mosquito-proof houses to protect migratory rice farmers from mosquito-borne illnesses. He is
								interested in the control of vector borne diseases, specifically in understanding the role of migratory
								livelihoods in maintaining the transmission of malaria. He is keen on developing research agendas
								that incorporate this aspect as well as the development and evaluation of novel mosquito control
								tools, particularly those that can be used by migratory communities.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="ff" style="position:static;z-index:0;display:none">
        {% include '../components/footer.html' %}
    </div>
</div>

{% endblock %}

templates/vcptUnit_team/teamPage.html
{% extends  '../baseTemplates/websiteBase.html' %}
{% load static %}
{% block title %} Team {% endblock %}
{% block content %}
<div class="team_section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12"  data-aos="zoom-in-up">
                <h1>VECTOR CONTROL PROJECT TEST UNIT</h1>
                <h1>TEAM</h1>
               
                </div>
        </div>
    </div>
</div>
<div class="team_message" data-aos="slide-up">
    <p><q>
        Between 2017 and 2021 the unit has undergone rapid expansion and now has outstanding research facilities and a team of 15 highly motivated research staff: PhD (4), MSc (8), BSc (4) with a growing number of female scientists (5). In addition to service contracts, the unit is actively engaged in applied research, with current research grants in the field of product development or bioassay development funded by many international donors and universities.
    </q></p>
</div>
<div class="team_gallarey">
    <div class="container">
        <div class="row">
            <div class="col-md-3 mt-5"  data-aos='zoom-out-up'  >
                <div class="inner_section">
                    <a href="{% url 'vcptUnit_team:SaraahMooredetailView' %}" class="link" style="text-decoration: none;color: black;">
                    <div class="image_section">
                        <img src="{% static './images/staff/Dr -saraah.png' %}" alt="" class="img-fluid">
                    </div>
                    <div class="description">
                        <h5>Dr. Sarah Moore</h5>
                        
                        <p>Head of unit</p>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-md-3 mt-5"  data-aos='zoom-out-up' >
                <div class="inner_section">
                    <a href="{% url 'vcptUnit_team:JasonMooredetailView' %}" class="link" style="text-decoration: none;color: black;">

                    <div class="image_section">
                        <img src="{% static './images/staff/jasonMoore.jpg' %}" alt="" class="img-fluid">
                        
                    </div>
                    <div class="description">
                        <h5>Jason Moore</h5>
                        
                        <p>Test Facility Manager</p>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-md-3 mt-5"  data-aos='zoom-out-up'  >
                <div class="inner_section">
                    <a href="{% url 'vcptUnit_team:EmmanuelMbubaDetailView' %}" class="link" style="text-decoration: none;color: black;">
                    <div class="image_section">
                        <img src="{% static './images/staff/EmmanuelMbuba_original web.png' %}" alt="" class="img-fluid">
                    </div>
                    <div class="description">
                        <h5>Emmanuel Mbuba</h5>
                        
                        <p>Study Director</p>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-md-3 mt-5"  data-aos='zoom-out-up' >
                <div class="inner_section">
                    <a href="{% url 'vcptUnit_team:RosePhilipoDetailView' %}" class="link" style="text-decoration: none;color: black;">

                    <div class="image_section">
                        <img src="{% static './images/staff/rose.png' %}" alt="" class="img-fluid">
                    </div>
                    <div class="description">
                        <h5>Rose Philipo</h5>
                        
                        <p>Project Manager</p>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-md-3 mt-5"  data-aos='zoom-out-up' >
                <div class="inner_section">
                    <div class="image_section">
                        <img src="{% static './images/staff/Chausiku.jpg' %}" alt="" class="img-fluid">
                    </div>
                    <div class="description">
                        <h5>Chausiku Mwinyimvua</h5>
                        
                        <p>Technician</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 mt-5"  data-aos='zoom-out-up'>
                <div class="inner_section">
                    <div class="image_section">
                        <img src="{% static './images/staff/Edga-Mbeyella.jpg' %}" alt="" class="img-fluid">
                    </div>
                    <div class="description">
                        <h5>Edgar Mbeyela</h5>
                        
                        <p>Technician</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 mt-5"  data-aos='zoom-out-up'>
                <div class="inner_section">
                    <div class="image_section">
                        <img src="{% static './images/staff/Dickson-Kobes.jpg' %}" alt="" class="img-fluid">
                    </div>
                    <div class="description">
                        <h5>Dickson Kobe</h5>
                        
                        <p>Technician</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 mt-5"  data-aos='zoom-out-up'>
                <div class="inner_section">
                    <div class="image_section">
                        <img src="{% static './images/staff/Ester-Gitetaa.jpg' %}" alt="" class="img-fluid">
                    </div>
                    <div class="description">
                        <h5>Ester Giteta</h5>
                        
                        <p>Administrative Officer</p>
                    </div>
                </div>
            </div>
           
            <!-- <a > -->
                <div class="col-md-3 mt-5"  data-aos='zoom-out-up'>
                    <a href="{% url 'vcptUnit_team:detailView' %}" class="link" style="text-decoration: none;color: black;">
                        <div class="inner_section">
                            <div class="image_section">
                                <img src="{% static './images/staff/Mmbaga-Sele.jpg' %}" alt="" class="img-fluid">
                            </div>
                            <div class="description">
                                <h5>Selemani Mmbaga</h5>
                                
                                <p>Data Manager</p>
                            </div>
                        </div>
                    </a>
                </div>
            <!-- </a> -->
            <div class="col-md-3 mt-5"  data-aos='zoom-out-up'>
                <div class="inner_section">
                    <a href="{% url 'vcptUnit_team:swaiDetailView' %}" class="link" style="text-decoration: none;color: black;">

                    <div class="image_section">
                        <img src="{% static './images/staff/Swai-Kyeba.jpg' %}" alt="" class="img-fluid">
                    </div>
                    <div class="description">
                        <h5>Swai Kyeba</h5>
                        
                        <p>Research Officer</p>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-md-3 mt-5"  data-aos='zoom-out-up'>
                <div class="inner_section">
                    <div class="image_section">
                        <img src="{% static './images/staff/Ritha-Kidyala.jpg'%}" alt="" class="img-fluid">
                    </div>
                    <div class="description">
                        <h5>Ritha Kidyala</h5>
                        
                        <p>Administrative Officer</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% include '../components/footer.html' %}

{% endblock %}