vcptUnit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vcptUnit_home.urls', namespace='vcptUnit_home')),
    path('vcptu-contact', include('vcptUnit_contact.urls', namespace='vcptUnit_contact')),
    path('about-vcptu', include('vcptUnit_aboutUs.urls', namespace='vcptUnit_aboutus')),
    path('vcptu-services', include('vcptUnit_service.urls', namespace='vcptUnit_service')),
    path('vcptu-facility', include('vcptUnit_facility.urls', namespace='vcptUnit_facility')),
    path('vcptu-publication', include('vcptUnit_publication.urls', namespace='vcptUnit_publication')),
    path('vcptu-projects', include('vcptUnit_projects.urls', namespace='vcptUnit_projects')),
    path('vcptu-accreditation', include('vcptUnit_accreditations.urls', namespace='vcptUnit_accreditations')),
    path('vcptu-news', include('vcptUnit_news.urls', namespace='vcptUnit_news')),
    # path('vcptu-reports', include('vcptUnit_reports.urls', namespace='vcptUnit_reports')),
    path('vcptu-team', include('vcptUnit_team.urls', namespace='vcptUnit_team')),
    path('vcptu-gallery', include('vcptUnit_gallery.urls', namespace='vcptUnit_gallery')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

vcptUnit_aboutUs/urls.py
from django.urls import path
from . import views

# urlsPatterns

app_name = 'vcptUnit_aboutus'

urlpatterns = [
    path('', views.aboutPage, name='aboutPage')
]

vcptUnit_home/urls.py
from django.urls import path
from vcptUnit_home import views

# urlsPatterns

app_name = 'vcptUnit_home'

urlpatterns = [
    path('', views.homePage, name='homePage')
]

vcptUnit_news/urls.py
from django.urls import path
from . import views

# urlsPatterns

app_name = 'vcptUnit_news'

urlpatterns = [
    path('', views.newsPage, name='newsPage'),
    path('-corporate-social-responsibility', views.detailaViewPage, name='detailaViewPage'),
    path('-head-of-vectors-from-nmcp-visited-vcptu', views.headOfVectorControl, name='headOfVectorControl'),
    path('-engagement-of-ifakara-show-case', views.engagementNewsDetailView, name='engagementNewsDetailView'),
    path('-engagement-of-ifakara', views.engagementdetailaViewPage, name='engagementdetailaViewPage'),
    path('-head-of-control', views.headOfVectorControlFullDetailViewPage , name='headOfVectorControlFullDetailViewPage'),
]

vcptUnit_team/urls.py
from django.urls import path
from . import views

# urlsPatterns

app_name = 'vcptUnit_team'

urlpatterns = [
   path('', views.teamPage, name='teamPage'),
   path('staff-detail', views.detailView, name='detailView'),
   path('staff-detail-dr-saraah-Moore', views.SaraahMooredetailView, name='SaraahMooredetailView'),
   path('staff-detail-jason-Moore', views.JasonMooredetailView, name='JasonMooredetailView'),
   path('staff-detail-kyeba-swai', views.swaiDetailView, name='swaiDetailView'),
   path('staff-detail-Emmanuel-Mbuba', views.EmmanuelMbubaDetailView, name='EmmanuelMbubaDetailView'),
   path('staff-detail-Rose-Philipo', views.RosePhilipoDetailView, name='RosePhilipoDetailView'),
   
]

templates/components/contributors.html
{% load static %}
<div class="contributors_list">
  {% for contributor in get_all_user_or_cotributors %}
    {% if contributor.member_photo %}
      <img src="{{ contributor.member_photo.url }}" alt="">
    {% else %}
      <img src="{% static 'images/avatar.png' %}" alt="">
    {% endif %}
  {% endfor %}
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
</div>

templates/components/heroSectionWithVideo.html
{% load static %}
<!-- <div id="hero">
  <video playsinline autoplay muted loop poster="placeholder.jpg" id="bgvideo" width="100%" height="100vh">
  <source src="{% static './videos/test.mp4' %}" type="video/mp4">
  </video>
  <div class="front_text">
    <div class="container">
      <div class="row">
        <div class="col-md-8 offset-md-2">
          <div class="item" data-aos="zoom-in-up">
            <h1>VECTOR PROJECT TESTING UNIT</h1>
            <h5><strong>We check  & Recheack our result</strong></h5>
            <div class="button_section">
              <a href="" class="our_service_link" >view our services</a>
            </div> 
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div> -->
<!-- 
<header>
  <div class="overlay"></div>
  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop" data-video="0">
    
      <source src="{% static './videos/test.mp4' %}" type="video/mp4">
    
  </video>
  <div class="container h-100">
    <div class="d-flex h-100 text-center align-items-center">
      <div class="w-100 text-white">
        <h1 class="wow zoomIn" data-wow-delay="1s">We're a world class research Institute</h1>
        <h2 class="lead mb-0 wow fadeIn" data-wow-delay="2s"> We exist to improve health and wellbeing of people</h2>
      </div>
    </div>
  </div>
</header> -->


<!-- <video loop muted autoplay playsinline poster="URL/TO/poster.jpg" class="background-video">
  <source src="{% static './videos/test.mp4' %}" type="video/mp4">
  <source src="URL/TO/video.webm" type="video/webm">
  <source src="URL/TO/video.ogv" type="video/ogv">
</video>

<div class="background-video-content">
  Your Element content in here.
</div> -->


<header>
  <!--- header --->
</header>

<main>
  <section id="hero-video">
    <div id="hero">
      <video playsinline autoplay muted loop poster="placeholder.jpg" id="bgvideo" width="100%" height="100vh">
        <source src="{% static './videos/Ifakara Health Institute.mp4' %}" type="video/mp4">
      </video>
      <div class="front_text">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="item" data-aos="zoom-in-up">
                <h1>VECTOR CONTROL PRODUCT</h1>
                <h1>TESTING UNIT</h1>
                <h5><strong>We Check & Recheck Our Results</strong></h5>
                <div class="button_section">
                  <!-- <a href="{% url  'vcptUnit_service:servicesPage' %}" class="our_service_link">view our services</a> -->
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

templates/components/horizontalLine.html
<div class="green_horizontal_line_section">
</div>

templates/components/messageFromDirector.html
{% load static %}
<div class="messages_section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="inner">
          <div class="message">
            <h4>Message from Head of Unit</h4>
            {% include 'components/topHorizontalLIne.html' %}
            <div style="width: 270px;">

            </div>

            <p><q>
                We serve the community through excellence in service delivery, research into new methods of product testing and training of MSc and PhD students.

                Having a diverse range of vector control tools in the malaria control toolbox has two advantages: 1) malaria control programs can select tools most suitable for their setting and 2) increasing market diversity creates competition that drives down unit costs of products.
              </q></p>

          </div>
          <div class="image_section" data-aos="slide-left">
            <a href="{% url 'vcptUnit_team:SaraahMooredetailView' %}" class="link" style="text-decoration: none;color: black;">

              <img src="{% static './images//Dr -saraah.JPG' %}" alt="" class="img-fluid">
              <div class="title">
                <h5>Dr Sarah Moore</h5>
                <h6> Head of unit</h6>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/components/navigation.html
{% load static %}
<div class="navigation_section_one">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="inner_section">
          <div class="logo_section">
            <a href="#">
              <img src="{% static './images/logo.png' %}" alt="" class="img-fluid " style="width: 100%;">
            </a>
          </div>
          <div class="address_section ">
            <!-- <div class="item1" style="display: flex;">
              <div class="image_section">
              <img src="{% static './images/greenLocation.png' %}" alt="" class="img-fluid" style="width: 60px;padding: 20px 10px;">
              </div>
              <div class="description" style="padding-top:15px;color: black;">
              <h6>Dar Es Salaam Office</h6>
              <span>#5 ifakara Street, Plot 463 Mikocheni</span>
              </div>
            </div> -->
            <div class="item1" style="display: flex;">
              <div class="image_section" style="width:120px">
                <img src="{% static './images/SANAS-Logo.png' %}" alt="" srcset="" class="img-fluid">
              </div>
              <div class="description" style="padding-top: 15px;color: black;">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="navigation_section_two" style="box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px;">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <hr style="padding: 1px;margin: 1px;">
        <div class="item">

          <nav class="navbar navbar-expand-lg">
            <!-- <div class="logo_section" >
			  <a class="navbar-brand" href="#">
				<img src="{% static './images/logo.png' %}" alt="" class="img-fluid">
			  </a>
			 </div> -->
            <div class="button_section">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            </div>
            <div class="collapse navbar-collapse  " id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'vcptUnit_home:homePage' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'vcptUnit_aboutus:aboutPage' %}">About</a>
                </li>
                <!-- <li class="nav-item">
                  <a class="nav-link" href="{% url 'vcptUnit_service:servicesPage' %}">Services</a>
                </li> -->
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'vcptUnit_facility:facilityPage' %}">Facility</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'vcptUnit_team:teamPage' %}">Team</a>
                </li>

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Research
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'vcptUnit_publication:publicationPage' %}">Publication</a></li>
                    <li><a class="dropdown-item" href="{% url 'vcptUnit_projects:projectPage' %}">Project</a></li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'vcptUnit_accreditations:accreditationPage' %}">Accreditations</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'vcptUnit_news:newsPage' %}">News</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'vcptUnit_contact:contactPage' %}">Contact</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'vcptUnit_gallery:galleryPage' %}">Gallery</a>
                </li>
                <!-- <li class="nav-item">
					<a class="nav-link" href="#">
					  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
						<path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
					  </svg>
					</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="#">
					  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
						<path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
					  </svg>
					</a>
				  </li> -->
                <li class="nav-item">
                  <button type="button" class="btn btn-outline-white p-0" data-bs-toggle="modal">
                    <span class="nav-link"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                      </svg>
                  </button>
                </li>
              </ul>
            </div>

          </nav>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" tabindex="0">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Serch content</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <form action="">
                  <input type="text" class="form-control">
                </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <!-- <button type="button" class="btn btn-primary">Understood</button> -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/components/oldNv.html
{% load static %}
<div class="navigation_section">
	<div class="container-fluid">
	  <div class="row">
		<div class="col-md-12">
		  <div class="inner">
			<div class="logo_section">
			  <a href="#">
				<img src="{% static './images/logo.png' %}" alt="" class="img-fluid " style="width: 100%;">
			  </a>
			</div>
			<div class="address_section ">
			  <!-- <div class="item1" style="display: flex;">
			  <div class="image_section">
				<img src="{% static './images/greenLocation.png' %}" alt="" class="img-fluid" style="width: 60px;padding: 20px 10px;">
			  </div>
			  <div class="description" style="padding-top:15px;color: black;">
				<h6>Dar Es Salaam Office</h6>
				<span>#5 ifakara Street, Plot 463 Mikocheni</span>
			  </div>
			</div> -->
			  <div class="item1" style="display: flex;">
				<div class="image_section">
				  <img src="{% static './images/greenLocation.png' %}" alt="" class="img-fluid" style="width: 60px;padding: 20px 10px;">
				</div>
				<div class="description" style="padding-top: 15px;color: black;">
				  <h6>
					Bagamoyo Branch</h6>
				  <span>Off Chuguni Road - Bagamoyo</span>
				</div>
			  </div>
			</div>
		  </div>
		</div>
	  </div>
	</div>
  
  
	<div class="container">
	  <div class="row">
		<div class="col-md-12">
		  <hr style="padding: 1px;margin: 1px;">
		  <div class="item">
			<nav class="navbar navbar-expand-lg">
			  <!-- <div class="logo_section" >
			  <a class="navbar-brand" href="#">
				<img src="{% static './images/logo.png' %}" alt="" class="img-fluid">
			  </a>
			 </div> -->
			  <div class="button_section">
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				  <span class="navbar-toggler-icon"></span>
				</button>
			  </div>
			  <div class="collapse navbar-collapse  " id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				  <li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{% url 'vcptUnit_home:homePage' %}">Home</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'vcptUnit_aboutus:aboutPage' %}">About</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'vcptUnit_service:servicesPage' %}">Services</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'vcptUnit_facility:facilityPage' %}">Facility</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'vcptUnit_team:teamPage' %}">Team</a>
				  </li>
  
				  <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
					  Research
					</a>
					<ul class="dropdown-menu">
					  <li><a class="dropdown-item" href="{% url 'vcptUnit_publication:publicationPage' %}">Publication</a></li>
					  <li><a class="dropdown-item" href="{% url 'vcptUnit_projects:projectPage' %}">Project</a></li>
					</ul>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'vcptUnit_accreditations:accreditationPage' %}">Accreditations</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'vcptUnit_news:newsPage' %}">News</a>
				  </li>
  
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'vcptUnit_contact:contactPage' %}">Contact</a>
				  </li>
				  <!-- <li class="nav-item">
					<a class="nav-link" href="#">
					  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
						<path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
					  </svg>
					</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="#">
					  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
						<path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
					  </svg>
					</a>
				  </li> -->
				  <li class="nav-item">
					<button type="button" class="btn btn-outline-white p-0" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
					  <span class="nav-link"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
						  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
						</svg>
					</button>
				  </li>
				</ul>
			  </div>
  
			</nav>
		  </div>
		</div>
	  </div>
	</div>
	<div class="container">
	  <div class="row">
		<div class="col-md-12">
		  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
			<div class="modal-dialog">
			  <div class="modal-content">
				<div class="modal-header">
				  <h1 class="modal-title fs-5" id="staticBackdropLabel">Serch content</h1>
				  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
				  <form action="">
					<input type="text" class="form-control">
				  </form>
				</div>
				<div class="modal-footer">
				  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
				  <!-- <button type="button" class="btn btn-primary">Understood</button> -->
				</div>
			  </div>
			</div>
		  </div>
		</div>
	  </div>
	</div>
  
  </div>

templates/components/staff.html
{% load static %}
<div class="staff_section">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="title text-center p-5">
          <h3>Core Managements Team</h3>
        </div>
        <div class="inner_staff_list">
          
            <div class="staff" data-aos="zoom-in-up">
              <a href="{% url 'vcptUnit_team:SaraahMooredetailView' %}" class="link" style="text-decoration: none;color: black;">

              <div class="image_section">
                <img src="{% static './images/staff/Dr -saraah.png' %}" alt="" class="img-fluid">
              </div>
              <div class="staff_title">
                <h5>Dr Sarah Moore</h5>
                <h5>Head of unit</h5>
              
              </div>
            </a>
            </div>
          <div class="staff" data-aos="zoom-in-up">
            <a href="{% url 'vcptUnit_team:JasonMooredetailView' %}" class="link" style="text-decoration: none;color: black;">
            <div class="image_section">
              <img src="{% static './images/staff/jasonMoore.jpg' %}" alt="" class="img-fluid">
            </div>
            <div class="staff_title">
              <h5>Jason Moore</h5>
              <h5>Test Facility Manager</h5>
            </div>
          </a>
          </div>
          <div class="staff">
            <a href="{% url 'vcptUnit_team:EmmanuelMbubaDetailView' %}" class="link" style="text-decoration: none;color: black;">
            {% comment %} EmmanuelMbubaDetailView {% endcomment %}
            <div class="image_section" data-aos="zoom-in-up">
              <img src="{% static './images/staff/EmmanuelMbuba_original web.png' %}" alt="" class="img-fluid" >
            </div>
            <div class="staff_title">
              <h5>Emmanuel Mbuba</h5>
              <h5>Study Director</h5>
            </div>
          </a>
          </div>
          <div class="staff">
            <a href="{% url 'vcptUnit_team:RosePhilipoDetailView' %}" class="link" style="text-decoration: none;color: black;">
            
            <div class="image_section" data-aos="zoom-in-up" style="background-color: white;">
              <img src="{% static './images/staff/rose.png' %}" alt="" class="img-fluid" >
            </div>
            <div class="staff_title">
              <h5>Rose Philipo</h5>
              <h5>Project Manager</h5>
            </div>
          </a>
          </div>
        </div>
      </div>
    </div>
  </div>



  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="title text-center p-5">
          <h3>Core Managements Team</h3>
        </div>
        <div class="inner_staff_list">
          
          <div class="staff" data-aos="zoom-in-up">
            <a href="{% url 'vcptUnit_team:SaraahMooredetailView' %}" class="link" style="text-decoration: none;color: black;">

            <div class="image_section">
              <img src="{% static './images/staff/Dr -saraah.png' %}" alt="" class="img-fluid">
            </div>
            <div class="staff_title">
              <h5>Dr Sarah Moore</h5>
              <h5>Head of unit</h5>
            
            </div>
          </a>
          </div>
          <div class="staff" data-aos="zoom-in-up">
            <div class="image_section">
              <img src="{% static './images/staff/Jason-Moore-VCPTU.png' %}" alt="" class="img-fluid">
            </div>
            <div class="staff_title">
              <h5>Jason Moore</h5>
              <h5>Test Facility Manager</h5>
            </div>
          </div>
          <div class="staff">
            <a href="{% url 'vcptUnit_team:EmmanuelMbubaDetailView' %}" class="link" style="text-decoration: none;color: black;">
            {% comment %} EmmanuelMbubaDetailView {% endcomment %}
            <div class="image_section" data-aos="zoom-in-up">
              <img src="{% static './images/staff/EmmanuelMbuba_original web.png' %}" alt="" class="img-fluid" >
            </div>
            <div class="staff_title">
              <h5>Emmanuel Mbuba</h5>
              <h5>Study Director</h5>
            </div>
          </a>
          </div>
          <div class="staff">
            <a href="{% url 'vcptUnit_team:RosePhilipoDetailView' %}" class="link" style="text-decoration: none;color: black;">
            
            <div class="image_section" data-aos="zoom-in-up" style="background-color: white;">
              <img src="{% static './images/staff/rose.png' %}" alt="" class="img-fluid" >
            </div>
            <div class="staff_title">
              <h5>Rose Philipo</h5>
              <h5>Project Manager</h5>
            </div>
          </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>